Config = {}

Config.Objects = {
    ["cone"] = {model = `prop_roadcone02a`, freeze = false},
    ["barrier"] = {model = `prop_barrier_work06a`, freeze = true},
    ["roadsign"] = {model = `prop_snow_sign_road_06g`, freeze = true},
    ["tent"] = {model = `prop_gazebo_03`, freeze = true},
    ["light"] = {model = `prop_worklight_03b`, freeze = true},
}

Config.MaxSpikes = 5

Config.HandCuffItem = 'handcuffs'

Config.LicenseRank = 2
Config.Locations = {
    ["duty"] = {
        [1] = vector3(616.29, -0.76, 82.74),
        [2] = vector3(616.29, -0.76, 82.74),
    },
    ["vehicle"] = {
    },
    ["stash"] = {
    },
    ["impound"] = {
    },
    ["helicopter"] = {
        [1] = vector4(449.47, -981.26, 44.06, 90.97),
        [2] = vector4(-475.43, 5988.353, 31.716, 31.34),
        [3] = vector4(1833.5, 3668.98, 39.29, 208.72),
        [4] = vector4(-475.28, 5988.25, 31.99, 315.58),
        [5] = vector4(123.19, -740.34, 263.21, 159.2),
        [6] = vector4(382.51, -1624.94, 29.66, 135.6),
    },
    ["armory"] = {
    },
    ["trash"] = {
    },
    ["fingerprint"] = {
    },
    ["evidence"] = {
    },
    ["stations"] = {
        [1] = {label = "Police Station", coords = vector4(446.33, -982.44, 30.69, 92.67)},
        [2] = {label = "Prison", coords = vector4(1845.903, 2585.873, 45.672, 272.249)},
        [3] = {label = "Sandy Sheriff", coords = vector4(1864.41, 3692.02, 34.24, 26.64), sheriff = true},
        [4] = {label = "paleto Sheriff", coords = vector4(-444.6, 6008.35, 32.29, 125.33), sheriff = true},
        [5] = {label = "FBI", coords = vector4(130.19, -763.01, 45.76, 61.21), fbi = true},
        [6] = {label = "SWAT", coords = vector4(371.67, -1600.83, 30.05, 317.28), swat = true},
    },
}

Config.ArmoryWhitelist = {}

Config.PoliceHelicopter = "polas350"
Config.SheriffHelicopter = "polas350"
Config.fbiHelicopter = "polas350"
Config.swatHelicopter = "polas350"

Config.SecurityCameras = {
    hideradar = false,
    cameras = {
        [1] = {label = "Pacific Bank CAM#1", coords = vector3(257.45, 210.07, 109.08), r = {x = -25.0, y = 0.0, z = 28.05}, canRotate = false, isOnline = true},
        [2] = {label = "Pacific Bank CAM#2", coords = vector3(232.86, 221.46, 107.83), r = {x = -25.0, y = 0.0, z = -140.91}, canRotate = false, isOnline = true},
        [3] = {label = "Pacific Bank CAM#3", coords = vector3(252.27, 225.52, 103.99), r = {x = -35.0, y = 0.0, z = -74.87}, canRotate = false, isOnline = true},
        [4] = {label = "Limited Ltd Grove St. CAM#1", coords = vector3(-53.1433, -1746.714, 31.546), r = {x = -35.0, y = 0.0, z = -168.9182}, canRotate = false, isOnline = true},
        [5] = {label = "Rob's Liqour Prosperity St. CAM#1", coords = vector3(-1482.9, -380.463, 42.363), r = {x = -35.0, y = 0.0, z = 79.53281}, canRotate = false, isOnline = true},
        [6] = {label = "Rob's Liqour San Andreas Ave. CAM#1", coords = vector3(-1224.874, -911.094, 14.401), r = {x = -35.0, y = 0.0, z = -6.778894}, canRotate = false, isOnline = true},
        [7] = {label = "Limited Ltd Ginger St. CAM#1", coords = vector3(-718.153, -909.211, 21.49), r = {x = -35.0, y = 0.0, z = -137.1431}, canRotate = false, isOnline = true},
        [8] = {label = "24/7 Supermarkt Innocence Blvd. CAM#1", coords = vector3(23.885, -1342.441, 31.672), r = {x = -35.0, y = 0.0, z = -142.9191}, canRotate = false, isOnline = true},
        [9] = {label = "Rob's Liqour El Rancho Blvd. CAM#1", coords = vector3(1133.024, -978.712, 48.515), r = {x = -35.0, y = 0.0, z = -137.302}, canRotate = false, isOnline = true},
        [10] = {label = "Limited Ltd West Mirror Drive CAM#1", coords = vector3(1151.93, -320.389, 71.33), r = {x = -35.0, y = 0.0, z = -119.4468}, canRotate = false, isOnline = true},
        [11] = {label = "24/7 Supermarkt Clinton Ave CAM#1", coords = vector3(383.102, 328.515, 105.541), r = {x = -35.0, y = 0.0, z = 118.585}, canRotate = false, isOnline = true},
        [12] = {label = "Limited Ltd Banham Canyon Dr CAM#1", coords = vector3(-1832.057, 789.389, 140.436), r = {x = -35.0, y = 0.0, z = -91.481}, canRotate = false, isOnline = true},
        [13] = {label = "Rob's Liqour Great Ocean Hwy CAM#1", coords = vector3(-2966.15, 387.067, 17.393), r = {x = -35.0, y = 0.0, z = 32.92229}, canRotate = false, isOnline = true},
        [14] = {label = "24/7 Supermarkt Ineseno Road CAM#1", coords = vector3(-3046.149, 592.191, 9.808), r = {x = -35.0, y = 0.0, z = -116.673}, canRotate = false, isOnline = true},
        [15] = {label = "24/7 Supermarkt Barbareno Rd. CAM#1", coords = vector3(-3246.089, 1010.008, 14.705), r = {x = -35.0, y = 0.0, z = -135.2151}, canRotate = false, isOnline = true},
        [16] = {label = "24/7 Supermarkt Route 68 CAM#1", coords = vector3(539.773, 2665.504, 43.556), r = {x = -35.0, y = 0.0, z = -42.947}, canRotate = false, isOnline = true},
        [17] = {label = "Rob's Liqour Route 68 CAM#1", coords = vector3(1169.855, 2711.493, 40.432), r = {x = -35.0, y = 0.0, z = 127.17}, canRotate = false, isOnline = true},
        [18] = {label = "24/7 Supermarkt Senora Fwy CAM#1", coords = vector3(2673.579, 3281.265, 57.541), r = {x = -35.0, y = 0.0, z = -80.242}, canRotate = false, isOnline = true},
        [19] = {label = "24/7 Supermarkt Alhambra Dr. CAM#1", coords = vector3(1966.24, 3748.80, 34.143), r = {x = -35.0, y = 0.0, z = 163.065}, canRotate = false, isOnline = true},
        [20] = {label = "24/7 Supermarkt Senora Fwy CAM#2", coords = vector3(1729.522, 6419.87, 37.262), r = {x = -35.0, y = 0.0, z = -160.089}, canRotate = false, isOnline = true},
        [21] = {label = "Fleeca Bank Hawick Ave CAM#1", coords = vector3(309.341, -281.439, 55.88), r = {x = -35.0, y = 0.0, z = -146.1595}, canRotate = false, isOnline = true},
        [22] = {label = "Fleeca Bank Legion Square CAM#1", coords = vector3(144.871, -1043.044, 31.017), r = {x = -35.0, y = 0.0, z = -143.9796}, canRotate = false, isOnline = true},
        [23] = {label = "Fleeca Bank Hawick Ave CAM#2", coords = vector3(-355.7643, -52.506, 50.746), r = {x = -35.0, y = 0.0, z = -143.8711}, canRotate = false, isOnline = true},
        [24] = {label = "Fleeca Bank Del Perro Blvd CAM#1", coords = vector3(-1214.226, -335.86, 39.515), r = {x = -35.0, y = 0.0, z = -97.862}, canRotate = false, isOnline = true},
        [25] = {label = "Fleeca Bank Great Ocean Hwy CAM#1", coords = vector3(-2958.885, 478.983, 17.406), r = {x = -35.0, y = 0.0, z = -34.69595}, canRotate = false, isOnline = true},
        [26] = {label = "Paleto Bank CAM#1", coords = vector3(-102.939, 6467.668, 33.424), r = {x = -35.0, y = 0.0, z = 24.66}, canRotate = false, isOnline = true},
        [27] = {label = "Del Vecchio Liquor Paleto Bay", coords = vector3(-163.75, 6323.45, 33.424), r = {x = -35.0, y = 0.0, z = 260.00}, canRotate = false, isOnline = true},
        [28] = {label = "Don's Country Store Paleto Bay CAM#1", coords = vector3(166.42, 6634.4, 33.69), r = {x = -35.0, y = 0.0, z = 32.00}, canRotate = false, isOnline = true},
        [29] = {label = "Don's Country Store Paleto Bay CAM#2", coords = vector3(163.74, 6644.34, 33.69), r = {x = -35.0, y = 0.0, z = 168.00}, canRotate = false, isOnline = true},
        [30] = {label = "Don's Country Store Paleto Bay CAM#3", coords = vector3(169.94, 6641.99, 33.69), r = {x = -35.0, y = 0.0, z = 5.0}, canRotate = false, isOnline = true},
        [31] = {label = "Vangelico Jewelery CAM#1", coords = vector3(-627.54, -239.74, 40.33), r = {x = -35.0, y = 0.0, z = 5.78}, canRotate = true, isOnline = true},
        [32] = {label = "Vangelico Jewelery CAM#2", coords = vector3(-627.51, -229.51, 40.24), r = {x = -35.0, y = 0.0, z = -95.78}, canRotate = true, isOnline = true},
        [33] = {label = "Vangelico Jewelery CAM#3", coords = vector3(-620.3, -224.31, 40.23), r = {x = -35.0, y = 0.0, z = 165.78}, canRotate = true, isOnline = true},
        [34] = {label = "Vangelico Jewelery CAM#4", coords = vector3(-622.57, -236.3, 40.31), r = {x = -35.0, y = 0.0, z = 5.78}, canRotate = true, isOnline = true},
        [35] = {label = "Money Factory CAM#1", coords = vector3(1006.7401123047,-2538.9362792969,30.734375), r = {x = -35.0, y = 0.0, z = -55.08}, canRotate = true, isOnline = true},
        [36] = {label = "Money Factory CAM#2", coords = vector3(1030.0301513672,-2535.8483886719,30.734375), r = {x = -35.0, y = 0.0, z = 125.08}, canRotate = true, isOnline = true},
    },
}


Config.WhitelistedVehicles = {}

Config.AmmoLabels = {
    ["AMMO_PISTOL"] = "9x19mm parabellum bullet",
    ["AMMO_SMG"] = "9x19mm parabellum bullet",
    ["AMMO_RIFLE"] = "7.62x39mm bullet",
    ["AMMO_MG"] = "7.92x57mm mauser bullet",
    ["AMMO_SHOTGUN"] = "12-gauge bullet",
    ["AMMO_SNIPER"] = "Large caliber bullet",
}

Config.Radars = {
	vector4(-623.44421386719, -823.08361816406, 25.25704574585, 145.0),
	vector4(-652.44421386719, -854.08361816406, 24.55704574585, 325.0),
	vector4(1623.0114746094, 1068.9924316406, 80.903594970703, 84.0),
	vector4(-2604.8994140625, 2996.3391113281, 27.528566360474, 175.0),
	vector4(2136.65234375, -591.81469726563, 94.272926330566, 318.0),
	vector4(2117.5764160156, -558.51013183594, 95.683128356934, 158.0),
	vector4(406.89505004883, -969.06286621094, 29.436267852783, 33.0),
	vector4(657.315, -218.819, 44.06, 320.0),
	vector4(2118.287, 6040.027, 50.928, 172.0),
	vector4(-106.304, -1127.5530, 30.778, 230.0),
	vector4(-823.3688, -1146.980, 8.0, 300.0),
}

Config.CarItems = {
    [1] = {
        name = "pdarmor",
        amount = 2,
        info = {},
        type = "item",
        slot = 1,
    },
    [2] = {
        name = "empty_evidence_bag",
        amount = 10,
        info = {},
        type = "item",
        slot = 2,
    },
    [3] = {
        name = "police_stormram",
        amount = 1,
        info = {},
        type = "item",
        slot = 3,
    },
}

Config.Items = {
    label = "Police Armory",
    slots = 31,
    items = {
        [1] = {
            name = "weapon_stungun",
            price = 20,
            amount = 1,
            info = {
                serie = "",
            },
            type = "weapon",
            slot = 1,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [2] = {
            name = "weapon_nightstick",
            price = 15,
            amount = 1,
            info = {},
            type = "weapon",
            slot = 2,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [3] = {
            name = "weapon_flashlight",
            price = 15,
            amount = 1,
            info = {},
            type = "weapon",
            slot = 3,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [4] = {
            name = "parachute",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [5] = {
            name = "handcuffs",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [6] = {
            name = "police_stormram",
            price = 30,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [7] = {
            name = "pdarmor",
            price = 5,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [8] = {
            name = "radio",
            price = 1,
            amount = 1,
            info = {},
            type = "item",
            slot = 8,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [9] = {
            name = "policespikes",
            price = 5,
            amount = 1,
            info = {},
            type = "item",
            slot = 9,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [10] = {
            name = "bodycam",
            price = 5,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [11] = {
            name = "dashcam",
            price = 3,
            amount = 1,
            info = {},
            type = "item",
            slot = 11,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [12] = {
            name = "ifaks",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 12,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [13] = {
            name = "bandage",
            price = 3,
            amount = 20,
            info = {},
            type = "item",
            slot = 13,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [14] = {
            name = "oxy",
            price = 3,
            amount = 20,
            info = {},
            type = "item",
            slot = 14,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [15] = {
            name = "drone_flyer_7",
            price = 15,
            amount = 1,
            info = {},
            type = "item",
            slot = 15,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [16] = {
            name = "policetablet",
            price = 15,
            amount = 1,
            info = {},
            type = "item",
            slot = 16,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [17] = {
            name = "pistol_ammo",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [18] = {
            name = "diving_gear",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 18,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [19] = {
            name = "weapon_smg",
            price = 70,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_SCOPE_MACRO_02", label = "1x Scope"},
                    {component = "COMPONENT_AT_AR_FLSH", label = "Flashlight"},
                }
            },
            type = "weapon",
            slot = 19,
            authorizedJobGrades = {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [20] = {
            name = "weapon_combatpdw",
            price = 100,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_SCOPE_MACRO_02", label = "1x Scope"},
                    {component = "COMPONENT_AT_AR_FLSH", label = "Flashlight"},
                }
            },
            type = "weapon",
            slot = 20,
            authorizedJobGrades = {5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [21] = {
            name = "weapon_specialcarbine_mk2",
            price = 130,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_AR_FLSH", label = "Flashlight"},
                    {component = "COMPONENT_AT_SCOPE_MEDIUM", label = "3x Scope"},
                }
            },
            type = "weapon",
            slot = 21,
            authorizedJobGrades = {6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [22] = {
            name = "weapon_m4",
            price = 200,
            amount = 1,
            info = {},
            type = "weapon",
            slot = 22,
            authorizedJobGrades = {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [23] = {
            name = "weapon_fn57",
            price = 60,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_PI_FLSH", label = "Flashlight"},
                }
            },
            type = "weapon",
            slot = 23,
            authorizedJobGrades = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [24] = {
            name = "weapon_glock",
            price = 50,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_PI_FLSH", label = "Flashlight"},
                }
            },
            type = "weapon",
            slot = 24,
            authorizedJobGrades = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [25] = {
            name = "smg_ammo",
            price = 3,
            amount = 50,
            info = {},
            type = "item",
            slot = 25,
            authorizedJobGrades = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [26] = {
            name = "rifle_ammo",
            price = 4,
            amount = 50,
            info = {},
            type = "item",
            slot = 26,
            authorizedJobGrades = {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
        [27] = {
            name = "weapon_microsmg",
            price = 5,
            amount = 10,
            info = {},
            type = "weapon",
            slot = 27,
            authorizedJobGrades = { 9, 10, 11, 12, 13, 14, 15, 16, 17}
        },
    }
}



Config.AuthorizedVehicles = {
	-- Grade 0
	[0] = {
        ["polvic"] = "CROWN VICTORIA",
        ["npolexp"] = "FORD EXPLORER",
	},
	-- Grade 1
	[1] = {
        ["polvic"] = "CROWN VICTORIA",
        ["npolexp"] = "FORD EXPLORER",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	-- Grade 2
	[2] = {
        ["polvic"] = "CROWN VICTORIA",
        ["poltaurus"] = "FORD TAURUS",
        ["npolexp"] = "FORD EXPLORER",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	-- Grade 3
	[3] = {
        ["polvic"] = "CROWN VICTORIA",
		["poltaurus"] = "FORD TAURUS",
        ["npolexp"] = "FORD EXPLORER",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	-- Grade 4
	[4] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolchar"] = "CHARGER 2018",
		["poltaurus"] = "FORD TAURUS",
        ["npolexp"] = "FORD EXPLORER",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	[5] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolchar"] = "CHARGER 2018",
		["poltaurus"] = "FORD TAURUS",
        ["npolexp"] = "FORD EXPLORER",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	[6] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolexp"] = "FORD EXPLORER",
		["npolchar"] = "CHARGER 2018",
		["npolstang"] = "FORD MUSTANG",
		--["polharley"] = 'polharley',
		-- ["polraptor"] = 'FORD RAPTOR',
		["poltah"] = "CHEVROLET TAHOE",
		["poltaurus"] = "FORD TAURUS",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	[7] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolexp"] = "FORD EXPLORER",
		["npolchar"] = "CHARGER 2018",
		["npolstang"] = "FORD MUSTANG",
		--["polharley"] = 'polharley',
		-- ["polraptor"] = 'FORD RAPTOR',
		["poltah"] = "CHEVROLET TAHOE",
		["poltaurus"] = "FORD TAURUS",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	[8] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolexp"] = "FORD EXPLORER",
		["npolchar"] = "CHARGER 2018",
		["npolstang"] = "FORD MUSTANG",
		--["polharley"] = 'polharley',
		-- ["polraptor"] = 'FORD RAPTOR',
		["poltah"] = "CHEVROLET TAHOE",
		["poltaurus"] = "FORD TAURUS",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	[9] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolexp"] = "FORD EXPLORER",
		["npolchar"] = "CHARGER 2018",
		["npolstang"] = "FORD MUSTANG",
		--["polharley"] = 'polharley',
		-- ["polraptor"] = 'FORD RAPTOR',
		["poltah"] = "CHEVROLET TAHOE",
		["poltaurus"] = "FORD TAURUS",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
	[10] = {
        ["polvic"] = "CROWN VICTORIA",
		["npolexp"] = "FORD EXPLORER",
		["npolchar"] = "CHARGER 2018",
		["npolstang"] = "FORD MUSTANG",
		--["polharley"] = 'polharley',
		-- ["polraptor"] = 'FORD RAPTOR',
		["poltah"] = "CHEVROLET TAHOE",
		["poltaurus"] = "FORD TAURUS",
        ["polmm"] = "Polmm",
        ["Kawasaki"] = "Kawasaki",
        ["pd_dirtbike"] = "DirtBike",
	},
}

Config.VehicleSettings = {
    ['lspd'] = {
        ["pd_dirtbike"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
        },
        ["Kawasaki"] = { --- Model name
            ["extras"] = {
                ["1"] = false, -- on/off
                ["2"] = false,
                ["3"] = false,
                ["4"] = false,
                ["5"] = false,
                ["6"] = false,
                ["7"] = false,
                ["8"] = false,
                ["9"] = false,
                ["10"] = false,
                ["11"] = false,
                ["12"] = false,
                ["13"] = false,
            },
            ['liv'] = 1,
        },
        ["polmm"] = { --- Model name
            ["extras"] = {
                ["1"] = false, -- on/off
                ["2"] = false,
                ["3"] = false,
                ["4"] = false,
                ["5"] = false,
                ["6"] = false,
                ["7"] = false,
                ["8"] = false,
                ["9"] = false,
                ["10"] = false,
                ["11"] = false,
                ["12"] = false,
                ["13"] = false,
            },
            ['liv'] = 0,
        },
        ["polvic"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
        },
        ["npolexp"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
            ['color1'] = 0,
            ['color2'] = 5,
        },
        ["npolstang"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 2,
            -- ['color1'] = 0,
            -- ['color2'] = 5,
            ['turbo'] = 1,
            ['en'] = 5,
        },
        ["npolchar"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
            ['color1'] = 67,
            ['color2'] = 0,
            ['turbo'] = 1,
            ['en'] = 5,
        },
        ["polharley"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
            ['color1'] = 0,
            ['color2'] = 0,
            ['turbo'] = 1,
            ['en'] = 5,
        },
        ["polraptor"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
            ['color1'] = 0,
            ['color2'] = 0,
            ['turbo'] = 1,
            ['en'] = 5,
        },
        ["poltah"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
            ['color1'] = 0,
            ['color2'] = 0,
            ['turbo'] = 1,
            ['en'] = 5,
        },
        ["poltaurus"] = { --- Model name
            ["extras"] = {
                ["1"] = true, -- on/off
                ["2"] = true,
                ["3"] = true,
                ["4"] = true,
                ["5"] = true,
                ["6"] = true,
                ["7"] = true,
                ["8"] = true,
                ["9"] = true,
                ["10"] = true,
                ["11"] = true,
                ["12"] = true,
                ["13"] = true,
            },
            ['liv'] = 0,
            ['color1'] = 0,
            ['color2'] = 0,
            ['turbo'] = 1,
            ['en'] = 5,
        },
    },
    -- ['sheriff'] = {
    --         ["pd_dirtbike"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 0,
    --     },
    --     ["Kawasaki"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = false, -- on/off
    --             ["2"] = false,
    --             ["3"] = false,
    --             ["4"] = false,
    --             ["5"] = false,
    --             ["6"] = false,
    --             ["7"] = false,
    --             ["8"] = false,
    --             ["9"] = false,
    --             ["10"] = false,
    --             ["11"] = false,
    --             ["12"] = false,
    --             ["13"] = false,
    --         },
    --         ['liv'] = 1,
    --     },
    --     ["polmm"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --     },
    --     ["polvic"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --     },
    --     ["npolexp"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --         ['color1'] = 0,
    --         ['color2'] = 5,
    --     },
    --     ["npolstang"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --         -- ['color1'] = 0,
    --         -- ['color2'] = 5,
    --         ['turbo'] = 1,
    --         ['en'] = 5,
    --     },
    --     ["npolchar"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 4,
    --         ['color1'] = 0,
    --         ['color2'] = 0,
    --         ['turbo'] = 1,
    --         ['en'] = 5,
    --     },
    --     ["polharley"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 0,
    --         ['color1'] = 0,
    --         ['color2'] = 0,
    --         ['turbo'] = 1,
    --         ['en'] = 5,
    --     },
    --     ["polraptor"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --         ['color1'] = 0,
    --         ['color2'] = 0,
    --         ['turbo'] = 1,
    --         ['en'] = 5,
    --     },
    --     ["poltah"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --         ['color1'] = 0,
    --         ['color2'] = 0,
    --         ['turbo'] = 1,
    --         ['en'] = 5,
    --     },
    --     ["poltaurus"] = { --- Model name
    --         ["extras"] = {
    --             ["1"] = true, -- on/off
    --             ["2"] = true,
    --             ["3"] = true,
    --             ["4"] = true,
    --             ["5"] = true,
    --             ["6"] = true,
    --             ["7"] = true,
    --             ["8"] = true,
    --             ["9"] = true,
    --             ["10"] = true,
    --             ["11"] = true,
    --             ["12"] = true,
    --             ["13"] = true,
    --         },
    --         ['liv'] = 1,
    --         ['color1'] = 0,
    --         ['color2'] = 0,
    --         ['turbo'] = 1,
    --         ['en'] = 5,
    --     },
    -- },
}

Config.Target = {
    ["policeArmory"] = {
        coords = vector3(482.58, -994.6, 30.69),
        name = "policeArmory",
        heading = 90,
        info1 = 1.2,
        info2 = 1,
        minZ=27.69,
        maxZ=31.69,
        debugPoly = false,
        distance = 3.0,
        type = "client", 
        event = "qb-police:policeArmory",  
        icon = 'fas fa-example', 
        label = 'Open Armory', 
        job = "police",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    ["swatArmory"] = {
        coords = vector3(365.15, -1604.38, 25.45),
        name = "SWATArmory",
        heading = 320,
        info1 = 1,
        info2 = 1,
        minZ=22.45,
        maxZ=26.45,
        debugPoly = false,
        distance = 3.0,
        type = "client", 
        event = "qb-police:swatArmory",  
        icon = 'fas fa-example', 
        label = 'Open Armory', 
        job = "swat",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    ["swatEvidence"] = {
        coords = vector3(379.0, -1610.45, 30.2),
        name = "swatEvidence",
        heading = 50,
        info1 = 2.2,
        info2 = 1,
        minZ=26.8,
        maxZ=30.8,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:swatEvidence",  
        icon = 'fas fa-example', 
        label = 'Evidence 1', 
        job = "swat",
        params = {id = 1},
        canInteract = function(entity)
            return true
        end,
    },
    ["swatPersonalStash"] = {
        coords = vector3(361.5, -1598.72, 25.45),
        name = "swatPersonalStash",
        heading = 140,
        info1 = 1.2,
        info2 = 1,
        minZ=23.25,
        maxZ=27.25,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:swatPersonalStash",  
        icon = 'fas fa-example', 
        label = 'Personal Stash', 
        job = "swat",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    ["fbiArmory"] = {
        coords = vector3(153.71, -757.7, 45.75),
        name = "FBIArmory",
        heading = 160,
        info1 = 2.0,
        info2 = 1,
        minZ=43.15,
        maxZ=47.15,
        debugPoly = false,
        distance = 3.0,
        type = "client", 
        event = "qb-police:fbiArmory",  
        icon = 'fas fa-example', 
        label = 'Open Armory', 
        job = "fbi",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    ["fbiEvidence"] = {
        coords = vector3(153.81, -751.45, 45.75),
        name = "fbiEvidence",
        heading = 70,
        info1 = 3.4,
        info2 = 1,
        minZ=43.35,
        maxZ=47.35,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:fbiEvidence",  
        icon = 'fas fa-example', 
        label = 'Evidence 1', 
        job = "fbi",
        params = {id = 1},
        canInteract = function(entity)
            return true
        end,
    },
    ["fbiPersonalStash"] = {
        coords = vector3(154.55, -755.53, 45.75),
        name = "fbiPersonalStash",
        heading = 340,
        info1 = 3.2,
        info2 = 1,
        minZ=43.75,
        maxZ=47.75,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:fbiPersonalStash",  
        icon = 'fas fa-example', 
        label = 'Personal Stash', 
        job = "fbi",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    -- ["policePersonalStash"] = {
    --     coords = vector3(477.04, -1006.92, 30.69),
    --     name = "policePersonalStash",
    --     heading = 0,
    --     info1 = 0.4,
    --     info2 = 3.4,
    --     minZ=29.69,
    --     maxZ=32.29,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policePersonalStash",  
    --     icon = 'fas fa-example', 
    --     label = 'Personal Stash', 
    --     job = "police",
    --     params = {},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- ["policeFinger"] = {
    --     coords = vector3(473.63, -1005.47, 26.21),
    --     name = "policeFinger",
    --     heading = 0,
    --     info1 = 0.6,
    --     info2 = 0.6,
    --     minZ=26.01,
    --     maxZ=26.61,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeFinger",  
    --     icon = 'fas fa-example', 
    --     label = 'FingerPrint', 
    --     job = "police",
    --     params = {},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    ["policeEvidence"] = {
        coords = vector3(448.94, -998.36, 30.69),
        name = "policeEvidence",
        heading = 90,
        info1 = 3.8,
        info2 = 1,
        minZ=27.69,
        maxZ=31.69,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:policeEvidence",  
        icon = 'fas fa-example', 
        label = 'Evidence 1', 
        job = "police",
        params = {id = 1},
        canInteract = function(entity)
            return true
        end,
    },
    -- ["policeEvidence2"] = {
    --     coords = vector3(461.65, -1006.46, 26.21),
    --     name = "policeEvidence2",
    --     heading = 0,
    --     info1 = 2.0,
    --     info2 = 0.4,
    --     minZ=25.21,
    --     maxZ=27.41,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeEvidence",  
    --     icon = 'fas fa-example', 
    --     label = 'Evidence 2', 
    --     job = "police",
    --     params = {id = 2},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- ["policeEvidence3"] = {
    --     coords = vector3(465.8, -1008.38, 26.21),
    --     name = "policeEvidence3",
    --     heading = 270,
    --     info1 = 2.0,
    --     info2 = 0.4,
    --     minZ=25.21,
    --     maxZ=27.41,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeEvidence",  
    --     icon = 'fas fa-example', 
    --     label = 'Evidence 3', 
    --     job = "police",
    --     params = {id = 3},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- ["policeEvidence4"] = {
    --     coords = vector3(465.82, -1006.79, 26.21),
    --     name = "policeEvidence4",
    --     heading = 270,
    --     info1 = 2.0,
    --     info2 = 0.4,
    --     minZ=25.21,
    --     maxZ=27.41,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeEvidence",  
    --     icon = 'fas fa-example', 
    --     label = 'Evidence 4', 
    --     job = "police",
    --     params = {id = 4},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- ["policeEvidence5"] = {
    --     coords = vector3(465.8, -1004.79, 26.21),
    --     name = "policeEvidence5",
    --     heading = 270,
    --     info1 = 2.0,
    --     info2 = 0.4,
    --     minZ=25.21,
    --     maxZ=27.41,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeEvidence",  
    --     icon = 'fas fa-example', 
    --     label = 'Evidence 5', 
    --     job = "police",
    --     params = {id = 5},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- ["policeEvidence6"] = {
    --     coords = vector3(465.91, -1003.05, 26.21),
    --     name = "policeEvidence6",
    --     heading = 270,
    --     info1 = 2.0,
    --     info2 = 0.4,
    --     minZ=25.21,
    --     maxZ=27.41,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeEvidence",  
    --     icon = 'fas fa-example', 
    --     label = 'Evidence 6', 
    --     job = "police",
    --     params = {id = 6},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- Sandy Sheriff Target
    ["sheriffArmory"] = {
        coords = vector3(1836.67, 3681.66, 38.93),
        name = "sheriffArmory",
        heading = 30,
        info1 = 3.0,
        info2 = 1,
        minZ=36.13,
        maxZ=40.13,
        debugPoly = false,
        distance = 3.0,
        type = "client", 
        event = "qb-police:policeArmory",  
        icon = 'fas fa-example', 
        label = 'Open Armory', 
        job = "sheriff",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    -- ["sheriffPersonalStash"] = {
    --     coords = vector3(1842.32, 3681.14, 34.19),
    --     name = "sheriffPersonalStash",
    --     heading = 210,
    --     info1 = 0.5,
    --     info2 = 3.4,
    --     minZ=31.39,
    --     maxZ=35.39,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policePersonalStash",  
    --     icon = 'fas fa-example', 
    --     label = 'Personal Stash', 
    --     job = "police",
    --     params = {},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    -- ["sheriffFinger"] = {
    --     coords = vector3(1818.94, 3665.94, 34.19),
    --     name = "sheriffFinger",
    --     heading = 330,
    --     info1 = 0.3,
    --     info2 = 0.5,
    --     minZ=33.99,
    --     maxZ=34.59,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeFinger",  
    --     icon = 'fas fa-example', 
    --     label = 'FingerPrint', 
    --     job = "police",
    --     params = {},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    ["sheriffEvidence"] = {
        coords = vector3(1857.14, 3680.58, 34.33),
        name = "sheriffEvidence",
        heading = 30,
        info1 = 3.2,
        info2 = 2,
        minZ=31.53,
        maxZ=35.53,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:policeEvidence",  
        icon = 'fas fa-example', 
        label = 'Sheriff Evidence', 
        job = "sheriff",
        params = {id = 8},
        canInteract = function(entity)
            return true
        end,
    },
       -- Paleto Sheriff Target
       ["sheriffPaletoArmory"] = {
        coords = vector3(-449.72, 6015.55, 37.0),
        name = "sheriffPaletoArmory",
        heading = 135,
        info1 = 0.9,
        info2 = 0.5,
        minZ = 33.85,
        maxZ = 37.85,
        debugPoly = false,
        distance = 3.0,
        type = "client", 
        event = "qb-police:policeArmory",  
        icon = 'fas fa-example', 
        label = 'Open Armory', 
        job = "sheriff",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    ["sheriffPaletoPersonalStash"] = {
        coords = vector3(-439.8, 6011.76, 37.0),
        name = "sheriffPaletoPersonalStash",
        heading = 315,
        info1 = 4.2,
        info2 = 0.5,
        minZ=34.2,
        maxZ=38.2,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:policePersonalStash",  
        icon = 'fas fa-example', 
        label = 'Personal Stash', 
        job = "sheriff",
        params = {},
        canInteract = function(entity)
            return true
        end,
    },
    -- ["sheriffPaletoFinger"] = {
    --     coords = vector3(-452.55, 5997.2, 27.58),
    --     name = "sheriffPaletoFinger",
    --     heading = 225,
    --     info1 = 0.7,
    --     info2 = 0.5,
    --     minZ=27.38,
    --     maxZ=28.18,
    --     debugPoly = false,
    --     distance = 2.0,
    --     type = "client", 
    --     event = "qb-police:policeFinger",  
    --     icon = 'fas fa-example', 
    --     label = 'FingerPrint', 
    --     job = "police",
    --     params = {},
    --     canInteract = function(entity)
    --         return true
    --     end,
    -- },
    ["sheriffPaletoEvidence"] = {
        coords = vector3(-453.26, 6000.01, 37.01),
        name = "sheriffPaletoEvidence",
        heading = 315,
        info1 = 1.3,
        info2 = 0.5,
        minZ=37.01,
        maxZ=38.01,
        debugPoly = false,
        distance = 2.0,
        type = "client", 
        event = "qb-police:policeEvidence",  
        icon = 'fas fa-example', 
        label = 'Sheriff Evidence', 
        job = "sheriff",
        params = {id = 9},
        canInteract = function(entity)
            return true
        end,
    },
}
